spring:
  application:
    name: property-service

  main:
    allow-bean-definition-overriding: true

  data:
    cassandra:
#      contact-points: 127.0.0.1
      keyspace-name: property_ks
#      port: 9042
      schema-action: create_if_not_exists
      local-datacenter: datacenter1

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "com.rental.propertysa.entity.Property"
        "[spring.json.trusted.packages]": "com.rental.propertysa.entity"

    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

    bootstrap-servers: "localhost:9092"


kafka:
  reservationTopic: "RESERVATION_TOPIC"

server:
  port: 8080