spring:
  application:
    name: property-service

  main:
    allow-bean-definition-overriding: true

  data:
    cassandra:
#      contact-points: 127.0.0.1
      keyspace-name: ${DB_KEYSPACE_NAME}
#      port: 9042
      schema-action: create_if_not_exists
      local-datacenter: ${DB_DATA_CENTER}

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "com.rental.propertysa.entity.Property"
        "[spring.json.trusted.packages]": "com.rental.propertysa.entity"

    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}


kafka:
  reservationTopic: ${KAFKA_RESERVATION_TOPIC}

server:
  port: ${SERVICE_PORT}