name: Build Docker on Release

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        
    - name: Execute Gradle bootJar
      run: ./gradlew bootJar
      
    - name: Print
      run: echo ${GITHUB_REF#refs/*/}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER_NAME}}/property-sa:${GITHUB_REF#refs/*/}
      
    - name: Docker Login
      env:
        DOCKER_USER_NAME: ${{secrets.DOCKER_USER_NAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
        
    - name: List of docker images
      run: docker images
      
    - name: Push to Docker Hub
      run: docker push ${{secrets.DOCKER_USER_NAME}}/property-sa:${GITHUB_REF#refs/*/}
